### ISSUE TITLE
A_gtex.dat not available for combined_analyses.ipynb

### ISSUE THREAD

**Issue by vjcitn** [SilviaLazzardi/Emergent_Laws_in_scRNA-seq_Data#5]
Wonderful repo.  I tried the docker compose approach noted in README
and went right to combined analysis and ran into
```
ArgumentError: "A_gtex.dat" is not a valid file or doesn't exist
```
in chunk 3 of combined_analyses.ipynb.  Did I miss a stage of data production?

**Comment by fvalle1** [comment]
Hi @vjcitn,

thanks for the interest in your repo. A_*.dat files should be saved when running [MouseCellAtlas/Mouse_Cell_Atlas_Data_Analysis.ipynb](https://github.com/SilviaLazzardi/Emergent_Laws_in_scRNA-seq_Data/blob/main/MouseCellAtlas/Mouse_Cell_Atlas_Data_Analysis.ipynb). *A* is the sum over columns (cells) of the expression values.

Anyway I have added them to the repo to make the analyses more straight-forward [[fea5418](https://github.com/SilviaLazzardi/Emergent_Laws_in_scRNA-seq_Data/commit/fea541860933b3f335a8ac3bbffff8cfd097728d)]
